#!/usr/bin/env python3
"""
Debug predicted topdown pose against GT pose on a 3RScan mesh.

Inputs (v1):
- Topdown image + camera sidecar generated by topdown_3rscan.py
- GT pose from first frame JSON under:
  <dataset_root>/<scene_id>/output/descriptions/frame-*.json
- Predicted topdown pixel (u, v) + heading omega (deg), hardcoded by default

Outputs:
- Interactive Open3D visualization with mesh, GT/pred points, direction arrows,
  and GT/pred camera frustums.
- Printed distance and angular errors.



python3 playground/testing/topdown_pose_debugger.py \
  --dataset-root /media/klrshak/Backup/Datasets/3RScan_processed \
  --scene-id 2e4a3962-d452-21a0-9fd2-7a325c600a49 \
  --pred-u 512 --pred-v 512 --pred-omega-deg 45 \
  --h-fov-deg 90 --v-fov-deg 60 --frustum-near-m 0.1 --frustum-far-m 1.2

"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Sequence, Tuple

import numpy as np
import open3d as o3d
from PIL import Image


PREFERRED_MESH_FILES = (
    "mesh.refined.v2.obj",
    "labels.instances.annotated.v2.ply",
    "mesh.refined.ply",
    "mesh.refined.obj",
    "mesh.obj",
)

# v1 default sample; can be overridden via CLI.
DEFAULT_SCENE_ID = "2e4a3962-d452-21a0-9fd2-7a325c600a49"
DEFAULT_PRED_U = 512.0
DEFAULT_PRED_V = 512.0
DEFAULT_PRED_OMEGA_DEG = 0.0

DEFAULT_EYE_HEIGHT_M = 1.6
DEFAULT_FLOOR_PERCENTILE = 1.0
DEFAULT_DIRECTION_STEP_PX = 20.0

DEFAULT_H_FOV_DEG = 90.0
DEFAULT_V_FOV_DEG = 60.0
DEFAULT_FRUSTUM_NEAR_M = 0.10
DEFAULT_FRUSTUM_FAR_M = 1.20


@dataclass(frozen=True)
class Pose3D:
    position: np.ndarray
    direction: Optional[np.ndarray]


@dataclass(frozen=True)
class ErrorMetrics:
    distance_m: float
    angular_error_deg: Optional[float]


def discover_mesh(scan_dir: Path) -> Path:
    for name in PREFERRED_MESH_FILES:
        path = scan_dir / name
        if path.exists():
            return path
    raise FileNotFoundError(f"No known mesh file found in {scan_dir}")


def load_mesh_vertices(mesh_path: Path) -> Tuple[o3d.geometry.TriangleMesh, np.ndarray]:
    mesh = o3d.io.read_triangle_mesh(str(mesh_path), enable_post_processing=True)
    if not mesh.has_vertex_normals():
        mesh.compute_vertex_normals()
    verts = np.asarray(mesh.vertices, dtype=np.float64)
    if verts.size == 0:
        raise RuntimeError(f"Mesh has no vertices: {mesh_path}")
    return mesh, verts


def find_first_frame_json(scene_dir: Path) -> Path:
    desc_dir = scene_dir / "output" / "descriptions"
    frames = sorted(desc_dir.glob("frame-*.json"))
    if not frames:
        raise FileNotFoundError(f"No frame JSON files found in {desc_dir}")
    return frames[0]


def load_gt_pose_from_first_frame(scene_dir: Path) -> Tuple[Pose3D, dict, Path]:
    frame_path = find_first_frame_json(scene_dir)
    frame = json.loads(frame_path.read_text())
    pose = np.asarray(frame.get("scene_pose"), dtype=np.float64)
    if pose.shape != (4, 4):
        raise ValueError(f"Expected scene_pose 4x4 in {frame_path}, got {pose.shape}")

    gt_pos = pose[:3, 3].astype(np.float64)
    gt_dir = pose[:3, :3] @ np.array([0.0, 0.0, 1.0], dtype=np.float64)
    gt_dir = normalize(gt_dir)
    return Pose3D(position=gt_pos, direction=gt_dir), frame, frame_path


def normalize(v: np.ndarray, eps: float = 1e-9) -> Optional[np.ndarray]:
    n = float(np.linalg.norm(v))
    if n < eps:
        return None
    return v / n


def load_topdown_camera(camera_path: Path) -> Tuple[np.ndarray, np.ndarray]:
    data = np.load(camera_path)
    k = np.asarray(data["intrinsic"], dtype=np.float64)
    e = np.asarray(data["extrinsic"], dtype=np.float64)
    if k.shape != (3, 3):
        raise ValueError(f"Intrinsic must be 3x3, got {k.shape} from {camera_path}")
    if e.shape != (4, 4):
        raise ValueError(f"Extrinsic must be 4x4, got {e.shape} from {camera_path}")
    return k, e


def read_image_size(image_path: Path) -> Tuple[int, int]:
    with Image.open(image_path) as im:
        w, h = im.size
    return w, h


def resolve_topdown_paths(scene_dir: Path, output_name: str) -> Tuple[Path, Path]:
    stem = Path(output_name).stem
    image_candidates = [
        scene_dir / output_name,
        scene_dir / "topdown.png",
        scene_dir / "topdown.pn",
    ]
    for img_path in image_candidates:
        cam_candidates = [
            img_path.with_name(f"{img_path.stem}_camera.npz"),
            scene_dir / "topdown_camera.npz",
            scene_dir / f"{stem}_camera.npz",
        ]
        for cam_path in cam_candidates:
            if img_path.exists() and cam_path.exists():
                return img_path, cam_path

    raise FileNotFoundError(
        "Could not find matching topdown image + camera sidecar. "
        f"Expected files in {scene_dir} (e.g., topdown.png + topdown_camera.npz)."
    )


def estimate_floor_z(frame: dict, vertices: np.ndarray, floor_percentile: float) -> float:
    visible = frame.get("visible_objects", {}) or {}
    floor_lows = []
    for obj in visible.values():
        label = str(obj.get("label", "")).strip().lower()
        if "floor" not in label:
            continue
        bbox = obj.get("bbox_world")
        if not isinstance(bbox, list) or len(bbox) != 2:
            continue
        try:
            lo = float(bbox[0][2])
            hi = float(bbox[1][2])
        except (TypeError, ValueError, IndexError):
            continue
        floor_lows.append(min(lo, hi))

    if floor_lows:
        return float(np.median(np.asarray(floor_lows, dtype=np.float64)))
    return float(np.percentile(vertices[:, 2], floor_percentile))


def camera_center_from_extrinsic(extrinsic_w2c: np.ndarray) -> np.ndarray:
    r = extrinsic_w2c[:3, :3]
    t = extrinsic_w2c[:3, 3]
    return (-r.T @ t).astype(np.float64)


def pixel_to_world_ray(u: float, v: float, intrinsic: np.ndarray, extrinsic_w2c: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    p = np.array([u, v, 1.0], dtype=np.float64)
    ray_cam = np.linalg.inv(intrinsic) @ p
    ray_cam = normalize(ray_cam)
    if ray_cam is None:
        raise ValueError("Invalid camera ray from intrinsic inversion.")

    r = extrinsic_w2c[:3, :3]
    ray_world = normalize(r.T @ ray_cam)
    if ray_world is None:
        raise ValueError("Invalid world-space ray direction.")

    center = camera_center_from_extrinsic(extrinsic_w2c)
    return center, ray_world


def intersect_ray_with_z_plane(ray_origin: np.ndarray, ray_dir: np.ndarray, z_plane: float) -> np.ndarray:
    dz = float(ray_dir[2])
    if abs(dz) < 1e-9:
        raise ValueError("Ray is parallel to fixed Z plane; cannot intersect.")
    lam = (z_plane - float(ray_origin[2])) / dz
    return ray_origin + lam * ray_dir


def pixel_to_world_on_z(u: float, v: float, intrinsic: np.ndarray, extrinsic_w2c: np.ndarray, z_plane: float) -> np.ndarray:
    origin, ray_dir = pixel_to_world_ray(u, v, intrinsic, extrinsic_w2c)
    return intersect_ray_with_z_plane(origin, ray_dir, z_plane)


def omega_to_world_direction(
    u: float,
    v: float,
    omega_deg: float,
    intrinsic: np.ndarray,
    extrinsic_w2c: np.ndarray,
    z_plane: float,
    step_px: float,
) -> Optional[np.ndarray]:
    # Convention: 0° = +u and CCW in image, so +90° points up (negative v).
    rad = math.radians(float(omega_deg))
    du = math.cos(rad) * step_px
    dv = -math.sin(rad) * step_px

    p0 = pixel_to_world_on_z(u, v, intrinsic, extrinsic_w2c, z_plane)
    p1 = pixel_to_world_on_z(u + du, v + dv, intrinsic, extrinsic_w2c, z_plane)
    d = p1 - p0
    d[2] = 0.0  # enforce floor-parallel direction
    return normalize(d)


def compute_errors(pred: Pose3D, gt: Pose3D) -> ErrorMetrics:
    dist = float(np.linalg.norm(pred.position - gt.position))
    if pred.direction is None or gt.direction is None:
        return ErrorMetrics(distance_m=dist, angular_error_deg=None)
    dot = float(np.clip(np.dot(pred.direction, gt.direction), -1.0, 1.0))
    ang = float(math.degrees(math.acos(dot)))
    return ErrorMetrics(distance_m=dist, angular_error_deg=ang)


def create_marker_sphere(center: np.ndarray, radius: float, color: Sequence[float]) -> o3d.geometry.TriangleMesh:
    sph = o3d.geometry.TriangleMesh.create_sphere(radius=radius)
    sph.compute_vertex_normals()
    sph.paint_uniform_color(np.asarray(color, dtype=np.float64))
    sph.translate(np.asarray(center, dtype=np.float64))
    return sph


def create_direction_line(
    center: np.ndarray,
    direction: Optional[np.ndarray],
    color: Sequence[float],
    length: float,
) -> Optional[o3d.geometry.LineSet]:
    if direction is None:
        return None
    d = normalize(np.asarray(direction, dtype=np.float64))
    if d is None:
        return None
    p0 = np.asarray(center, dtype=np.float64)
    p1 = p0 + d * float(length)
    line = o3d.geometry.LineSet()
    line.points = o3d.utility.Vector3dVector(np.vstack([p0, p1]))
    line.lines = o3d.utility.Vector2iVector(np.array([[0, 1]], dtype=np.int32))
    line.colors = o3d.utility.Vector3dVector(np.asarray([color], dtype=np.float64))
    return line


def create_camera_frustum(
    center: np.ndarray,
    direction: np.ndarray,
    hfov_deg: float,
    vfov_deg: float,
    near: float,
    far: float,
    color: tuple[float, float, float],
) -> Optional[o3d.geometry.LineSet]:
    d = normalize(np.asarray(direction, dtype=np.float64))
    if d is None:
        return None

    up = np.array([0.0, 0.0, 1.0], dtype=np.float64)
    if abs(float(np.dot(d, up))) > 0.95:
        up = np.array([0.0, 1.0, 0.0], dtype=np.float64)

    right = np.cross(d, up)
    right = normalize(right)
    if right is None:
        return None
    up = np.cross(right, d)
    up = normalize(up)
    if up is None:
        return None

    near = max(float(near), 1e-4)
    far = max(float(far), near + 1e-4)
    hf = math.radians(float(hfov_deg))
    vf = math.radians(float(vfov_deg))

    near_h = math.tan(vf * 0.5) * near
    near_w = math.tan(hf * 0.5) * near
    far_h = math.tan(vf * 0.5) * far
    far_w = math.tan(hf * 0.5) * far

    c = np.asarray(center, dtype=np.float64)
    near_c = c + d * near
    far_c = c + d * far

    near_corners = [
        near_c + right * near_w + up * near_h,
        near_c - right * near_w + up * near_h,
        near_c - right * near_w - up * near_h,
        near_c + right * near_w - up * near_h,
    ]
    far_corners = [
        far_c + right * far_w + up * far_h,
        far_c - right * far_w + up * far_h,
        far_c - right * far_w - up * far_h,
        far_c + right * far_w - up * far_h,
    ]

    points = np.vstack([c, *near_corners, *far_corners])
    lines = np.array(
        [
            [0, 1], [0, 2], [0, 3], [0, 4],  # apex to near corners
            [1, 2], [2, 3], [3, 4], [4, 1],  # near plane
            [5, 6], [6, 7], [7, 8], [8, 5],  # far plane
            [1, 5], [2, 6], [3, 7], [4, 8],  # near-to-far edges
        ],
        dtype=np.int32,
    )

    frustum = o3d.geometry.LineSet()
    frustum.points = o3d.utility.Vector3dVector(points)
    frustum.lines = o3d.utility.Vector2iVector(lines)
    frustum.colors = o3d.utility.Vector3dVector(
        np.tile(np.asarray(color, dtype=np.float64), (lines.shape[0], 1))
    )
    return frustum


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Topdown pose debugger with GT/pred camera frustum visualization."
    )
    parser.add_argument(
        "--dataset-root",
        type=Path,
        default=Path("/media/klrshak/Backup/Datasets/3RScan_processed"),
        help="Root containing <scene_id>/ mesh and frame JSONs.",
    )
    parser.add_argument(
        "--scene-id",
        type=str,
        default=DEFAULT_SCENE_ID,
        help="Scene ID to debug.",
    )
    parser.add_argument(
        "--output-name",
        type=str,
        default="topdown.png",
        help="Per-scene topdown filename when generated in all-scans mode.",
    )
    parser.add_argument("--pred-u", type=float, default=DEFAULT_PRED_U)
    parser.add_argument("--pred-v", type=float, default=DEFAULT_PRED_V)
    parser.add_argument("--pred-omega-deg", type=float, default=DEFAULT_PRED_OMEGA_DEG)
    parser.add_argument("--eye-height-m", type=float, default=DEFAULT_EYE_HEIGHT_M)
    parser.add_argument("--floor-percentile", type=float, default=DEFAULT_FLOOR_PERCENTILE)
    parser.add_argument("--direction-step-px", type=float, default=DEFAULT_DIRECTION_STEP_PX)
    parser.add_argument("--h-fov-deg", type=float, default=DEFAULT_H_FOV_DEG)
    parser.add_argument("--v-fov-deg", type=float, default=DEFAULT_V_FOV_DEG)
    parser.add_argument("--frustum-near-m", type=float, default=DEFAULT_FRUSTUM_NEAR_M)
    parser.add_argument("--frustum-far-m", type=float, default=DEFAULT_FRUSTUM_FAR_M)
    parser.add_argument("--arrow-length-m", type=float, default=0.8)
    parser.add_argument("--marker-radius-m", type=float, default=0.08)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    scene_dir = args.dataset_root / args.scene_id
    if not scene_dir.exists():
        raise FileNotFoundError(scene_dir)

    topdown_image, camera_npz = resolve_topdown_paths(scene_dir, args.output_name)
    img_w, img_h = read_image_size(topdown_image)
    k, e = load_topdown_camera(camera_npz)

    mesh_path = discover_mesh(scene_dir)
    mesh, vertices = load_mesh_vertices(mesh_path)

    gt_pose, frame, frame_path = load_gt_pose_from_first_frame(scene_dir)
    floor_z = estimate_floor_z(frame, vertices, args.floor_percentile)
    pred_z = floor_z + float(args.eye_height_m)

    if not (0.0 <= args.pred_u < img_w and 0.0 <= args.pred_v < img_h):
        print(
            f"[WARN] Predicted pixel ({args.pred_u:.2f}, {args.pred_v:.2f}) "
            f"is outside image bounds [0,{img_w})x[0,{img_h})."
        )

    pred_pos = pixel_to_world_on_z(args.pred_u, args.pred_v, k, e, pred_z)
    pred_dir = omega_to_world_direction(
        u=args.pred_u,
        v=args.pred_v,
        omega_deg=args.pred_omega_deg,
        intrinsic=k,
        extrinsic_w2c=e,
        z_plane=pred_z,
        step_px=args.direction_step_px,
    )
    pred_pose = Pose3D(position=pred_pos, direction=pred_dir)

    metrics = compute_errors(pred_pose, gt_pose)

    gt_marker = create_marker_sphere(gt_pose.position, args.marker_radius_m, (0.1, 0.8, 0.1))
    pred_marker = create_marker_sphere(pred_pose.position, args.marker_radius_m, (0.9, 0.1, 0.1))
    gt_dir_line = create_direction_line(gt_pose.position, gt_pose.direction, (0.1, 0.8, 0.1), args.arrow_length_m)
    pred_dir_line = create_direction_line(pred_pose.position, pred_pose.direction, (0.9, 0.1, 0.1), args.arrow_length_m)

    gt_frustum = create_camera_frustum(
        center=gt_pose.position,
        direction=gt_pose.direction if gt_pose.direction is not None else np.zeros(3),
        hfov_deg=args.h_fov_deg,
        vfov_deg=args.v_fov_deg,
        near=args.frustum_near_m,
        far=args.frustum_far_m,
        color=(0.1, 0.8, 0.1),
    )
    if gt_frustum is None:
        print("[WARN] GT frustum skipped due to invalid GT direction.")

    pred_frustum = create_camera_frustum(
        center=pred_pose.position,
        direction=pred_pose.direction if pred_pose.direction is not None else np.zeros(3),
        hfov_deg=args.h_fov_deg,
        vfov_deg=args.v_fov_deg,
        near=args.frustum_near_m,
        far=args.frustum_far_m,
        color=(0.9, 0.1, 0.1),
    )
    if pred_frustum is None:
        print("[WARN] Predicted frustum skipped due to invalid predicted direction.")

    print(f"Scene: {args.scene_id}")
    print(f"Frame: {frame.get('image_index', frame_path.name)} ({frame_path})")
    print(f"Topdown image: {topdown_image} ({img_w}x{img_h})")
    print(f"Camera sidecar: {camera_npz}")
    print(f"Pred pixel: (u={args.pred_u:.3f}, v={args.pred_v:.3f}), omega={args.pred_omega_deg:.3f} deg")
    print(f"Floor z estimate: {floor_z:.4f} m")
    print(f"Pred fixed z: {pred_z:.4f} m")
    print(
        "Frustum params: "
        f"hfov={args.h_fov_deg:.2f} deg, vfov={args.v_fov_deg:.2f} deg, "
        f"near={args.frustum_near_m:.3f} m, far={args.frustum_far_m:.3f} m"
    )
    print(f"GT position: {gt_pose.position.tolist()}")
    print(f"Pred position: {pred_pose.position.tolist()}")
    if gt_pose.direction is not None:
        print(f"GT direction: {gt_pose.direction.tolist()}")
    else:
        print("GT direction: n/a")
    if pred_pose.direction is not None:
        print(f"Pred direction: {pred_pose.direction.tolist()}")
    else:
        print("Pred direction: n/a")
    print(f"Distance error: {metrics.distance_m:.4f} m")
    if metrics.angular_error_deg is None:
        print("Angular error: n/a")
    else:
        print(f"Angular error: {metrics.angular_error_deg:.4f} deg")

    geoms: list[o3d.geometry.Geometry] = [mesh, gt_marker, pred_marker]
    if gt_dir_line is not None:
        geoms.append(gt_dir_line)
    if pred_dir_line is not None:
        geoms.append(pred_dir_line)
    if gt_frustum is not None:
        geoms.append(gt_frustum)
    if pred_frustum is not None:
        geoms.append(pred_frustum)

    o3d.visualization.draw_geometries(
        geoms,
        window_name=f"Topdown Pose Debugger - {args.scene_id}",
        width=1400,
        height=900,
        mesh_show_back_face=True,
    )


if __name__ == "__main__":
    main()
