_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 33
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 33
                - 53
                - 55
                - 77
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
"N":
    value: 1
architecture:
    value: self attention cross attention
batch_size:
    value: 16
continue_training:
    value: 0
continue_training_model:
    value: null
contrastive_loss:
    value: true
cos_sim_thr:
    value: 0.5
dataset:
    value: ScanScribe_cleaned
entire_training_set:
    value: false
epoch:
    value: 100
eval_entire_dataset:
    value: false
eval_iter_count:
    value: 10
eval_iters:
    value: 30
eval_only_c:
    value: false
folds:
    value: 10
graph_size_min:
    value: 4
heads:
    value: 2
loss_ablation_c:
    value: false
loss_ablation_m:
    value: true
lr:
    value: 0.0001
mode:
    value: online
model_name:
    value: model_NO_subg_100_epochs_30_eval_iters_loss_ablation_m_cut_cross
out_of:
    value: 10
overlap_thr:
    value: 0.8
scannet:
    value: false
scanscribe_auto_gen:
    value: false
skip_k_fold:
    value: true
subgraph_ablation:
    value: true
test_set_size:
    value: 712
training_set_size:
    value: 2847
training_with_cross_val:
    value: true
use_attributes:
    value: true
valid_top_k:
    value:
        - 1
        - 2
        - 3
        - 5
weight_decay:
    value: 5e-05
